# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-10 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('project_name', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('duration', models.CharField(choices=[('w', 'A week or two'), ('m', 'Around a month'), ('mm', 'Several months'), ('y', 'About a year'), ('o', 'Long-term (ongoing)'), ('?', 'Not sure yet')], max_length=7)),
                ('urgency', models.CharField(choices=[('1', 'ASAP (in one month or less)'), ('2', 'Soon (in 1-3 months)'), ('3', 'In 3 months or more')], max_length=7)),
            ],
        ),
    ]
