# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-20 22:08
from __future__ import unicode_literals
from django.contrib.auth.models import User

from django.db import migrations


def add_user_for_login_dashboard(apps, schema_editor):
    new_user = User.objects.create_user(username='team_player', password='dpixNumber1')
    new_user.save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_user_for_login_dashboard),
    ]
