#!/bin/bash
# This hook is run after this virtualenv is activated.

export DJANGO_SETTINGS_MODULE=config.prod_settings
export DATABASE_URL=%(DATABASE_URL)s
export DJANGO_DEBUG=False
export DJANGO_LOCAL=False
