# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 11:04
from __future__ import unicode_literals

from django.db import migrations

def add_data(apps, schema_editor):

    list_currancy = ['BTC', 'BCH', 'ETH', 'LTC', 'DASH', 'ZEC', 'XMR', 'ETC', 'XLM', 'XRP',
                     'LSK', 'EOS', 'BTG', 'NEO', 'OMG', 'BEX', 'BBD']

    Currancy = apps.get_model('core', 'Currency')
    for i in list_currancy:
        Currancy.objects.create(name=i)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_currency_investors'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
