# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-05 16:32
from __future__ import unicode_literals

from django.db import migrations


def remove_duplicates(apps, schema_editor):
    Subscribe = apps.get_model('core', 'Subscribe')
    subscribers_set = set()
    for entry in Subscribe.objects.all():
        if entry.email in subscribers_set:
            entry.delete()
        else:
            subscribers_set.add(entry.email)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171115_1104'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates)
    ]
