# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170707_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('link_github', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='team/')),
            ],
        ),
    ]
